name: 점심 자동 알림 슬랙봇

on:
  schedule:
    # UTC 기준 2시 = KST 오전 11시, 평일(월~금) 실행
    - cron: '0 0 * * 1-5'
  workflow_dispatch:  # 수동 실행도 가능하게 설정

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Slack notification script
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        CSV_URL: ${{ secrets.CSV_URL }}
      run: python main.py
